# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [ ]:
# vector is 1dimensional where Matrix is 2 dimensional.

**2. How to import `NumPy` library?** 

In [2]:
# To avoid overwriting the output, please code here 

In [1]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [4]:
list_1 = [1,2,3,4,5]

In [1]:
# To avoid overwriting the output, please code here 

In [3]:
list_2 = np.array([1,2,3,4,5])
print(type(list_2))

<class 'numpy.ndarray'>


**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [8]:
# To avoid overwriting the output, please code here 
arr = np.arange(0,6)
arr

array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [10]:
# To avoid overwriting the output, please code here 
arr = np.linspace(0,0,5)
arr

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [11]:
# To avoid overwriting the output, please code here 
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [12]:
# To avoid overwriting the output, please code here 
arr = np.linspace(1,1,5)
print(arr)

[1. 1. 1. 1. 1.]


[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [13]:
# To avoid overwriting the output, please code here 
arr = np.linspace(10,10,5)
arr

array([10., 10., 10., 10., 10.])

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [15]:
# To avoid overwriting the output, please code here 
arr = np.arange(52,99,2)
arr

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [16]:
# To avoid overwriting the output, please code here 
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [17]:
# To avoid overwriting the output, please code here 
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
# To avoid overwriting the output, please code here 
m_array = arr.reshape(5,5)
m_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
# To avoid overwriting the output, please code here 
arr.shape = (5,5)
arr

C:\Users\USER\AppData\Local\Temp\ipykernel_15640\3747885752.py:2: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  arr.shape = (5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [27]:
# To avoid overwriting the output, please code here 

In [26]:
arr = np.arange(0.1,2.6,0.1)
a =arr.reshape((5,5))
a

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [32]:
# To avoid overwriting the output, please code here 
arr = np.linspace(0,24,25, dtype=int)
a = arr.reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [31]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

**15. How to generate a single random integer number using NumPy built-in function?**

In [37]:
# To avoid overwriting the output, please code here 
a = np.random.randint(1,100)
a

80

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [38]:
# To avoid overwriting the output, please code here 
a = np.random.rand(7,5)
print(a)

[[0.52660601 0.97247375 0.80319787 0.97876407 0.17578016]
 [0.54171898 0.50744126 0.71128643 0.47547164 0.42372531]
 [0.3968068  0.26466871 0.30455881 0.47392259 0.19746033]
 [0.41311227 0.10823784 0.35892702 0.59926404 0.91023962]
 [0.98281715 0.47657093 0.21943806 0.40045908 0.25791872]
 [0.42877526 0.63766335 0.20513961 0.88406552 0.95248613]
 [0.96625828 0.36626973 0.59976683 0.09682099 0.24393144]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [41]:
# To avoid overwriting the output, please code here 
a = np.eye(5, dtype= int) * 5
a

array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5]])

array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 